First branch
mugishasam123/portfolio-website pull request #3
Opened 2021-11-22 11:04 UTC by mugishasam123

added homepage 
linters check
added  css

2021-11-22 12:16 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @mugishasam123, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Instead of having your icons as images, you should consider using something like [font awesome](https://fontawesome.com/), so they have more customizations options.

![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-22 12:16 UTC, VanessaAoki commented on style.css
> +  color: rgba(23, 43, 77, 1);
- [ ] To match the Figma design better, you should consider using the same colors. Did you know that you can get the exact color by clicking on the element? This is how it looks like:

![image](https://user-images.githubusercontent.com/66967274/142858328-900e4fe5-5a0b-4357-968a-7515c511a44a.png)

2021-11-22 12:16 UTC, VanessaAoki commented on style.css
> +  color: rgba(96, 112, 255, 1);
- [ ] As mentioned before, to match the Figma design better you should consider changing the color codes of your project, in this case it should be `#6070FF`.

2021-11-22 12:16 UTC, VanessaAoki commented on style.css
> +}
- [ ] Good job implementing the hover action for this links, even though the design does not provide you the stylings, you should consider using a color that still matches the whole design, what about the `#2230D2`? _(that's the pressed button action background color)_

2021-11-22 12:16 UTC, VanessaAoki commented on README.md
> +Additional description about the project and its features.
- [ ] Great job using Microverse's template, but in order to make it look more professional, don't forget to personalize it with your own project informations. For instance, instead of "Proejct Name", you could have "Mugisha's Portfolio".
- [ ] You should also edit this whole README file to match your project _(if you want some more inspiration you can check [this README](https://github.com/VanessaAoki/YouTubeClone) file)_.

2021-11-22 12:16 UTC, VanessaAoki commented on MIT.md
> +## Copyright 2021, [Mithlesh Kumar]
- [ ] You should consider having your own name in the license, unless this project is not yours.

2021-11-22 15:30 UTC, alonsofl requested changes
Hi @mugishasam123,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-22 15:30 UTC, alonsofl commented on index.html
> +        </nav>
- [ ] As the previous reviewer suggested, it is a good idea to change the structure of your header. I would suggest moving the `<a>` tag outside of the nav so it looks like this :wink:
```
<header>
  <a>UNIFY</a>
  <nav>
    <img />
  </nav>
</header>
```

2021-11-22 15:30 UTC, alonsofl commented on style.css
> +  color: rgba(23, 43, 77, 1);
- [ ] [OPTIONAL] It is fine to use the rgba(23, 43, 77, 1) option for colors since you get the same result, but I think it could be easier to maintain if you use regular HEX like `#172b4d`. It is totally up to you :wink:
![image](https://user-images.githubusercontent.com/81522435/142886583-fc72fa18-194e-4937-833d-a467a6128ffa.png)

2021-11-22 15:30 UTC, alonsofl commented on style.css
> +  color: rgba(96, 112, 255, 1);
- [ ] [OPTIONAL] Also here, you get the same result, but it could be more be easier to maintain if you use regular HEX colors :pushpin: :smiley:
![image](https://user-images.githubusercontent.com/81522435/142887381-12dd8a92-82a9-4620-afba-297f51962132.png)

2021-11-23 08:18 UTC, Rustamxon7 approved these changes
# Congratulations🎉 🎉 

## Hi @mugishasam123 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### HIGHLITES!

- No linter errors. 💯
- Descriptive README file. 💯
- You have followed the all given requirements. 💯

![giphy](https://user-images.githubusercontent.com/69011963/133281679-16a58f27-111e-4186-a4e3-19cc93cc19e7.gif)

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 08:29 UTC, merged